### PR TITLE
Add generated color listener

### PR DESCRIPTION
**Pull request by alorma**
With this update, developer can get the generated color in a simple mode

[Review on Reviewable](https://reviewable.io/reviews/musenkishi/atelier/7)

### CODE REVIEW

**Comment by alorma** [comment]
This will fix https://github.com/Musenkishi/Atelier/issues/6

**Comment by musenkishi** [comment]
I like the concept! But I think it'd be better to just change the `OnPaletteRenderedListener` to include the color:

``` java
public interface OnPaletteRenderedListener {
         void onRendered(Palette palette, int requestedColor);
}
```

What do you think?

**Comment by alorma** [comment]
It's ok for me in both ways

**Comment by alorma** [comment]
I will modify when i have time

**Comment by alorma** [comment]
Will do in a separate PR, i close this one

**Pull request closed without merging**
